/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:672c710c-e055-4604-abc6-ba94ed8a386a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qGHyQllXo",
    "aws_user_pools_web_client_id": "6c16sj34cbr6ah68slklmep346",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xru6yhgdhjfifbtdm5eolcsjna.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
